# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kh8BnYp95Y8lcbD2agVzOhG_Pgx_wOaC
"""

!pip install torchinfo

import pandas as pd
import numpy as np
from torchvision import datasets
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
import torch
import torch.nn as nn
from torchvision.transforms import transforms
from torchvision.models import resnet18, ResNet18_Weights
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
import torch.optim as optim
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from torchinfo import summary

!unzip skin_disease.zip -d data

data = datasets.ImageFolder("/content/data/train")

print(len(data))
print(data.classes)

fig, axes = plt.subplots(5, 4, figsize=(8, 8))
fig.suptitle("20 Images", fontsize=16)

for i, ax in enumerate(axes.flat):

  idx = random.randint(0,1494)
  img, label = data[idx]

  ax.imshow(img)
  ax.set_title(f"Label: {label}")
  ax.axis("off")

plt.tight_layout(rect=[0, 0, 1, 0.98])
plt.show()

X = []
y = []

for img, label in data:
    X.append(img)
    y.append(label)

X_train, X_temp, y_train, y_temp = train_test_split(X,y,test_size=0.3,random_state=0,stratify=y)
X_test, X_val, y_test, y_val = train_test_split(X_temp,y_temp,test_size=0.5,random_state=0,stratify=y_temp)

custom_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Added normalization
])

augment = transforms.Compose([
     transforms.RandomHorizontalFlip(),
     transforms.RandomRotation(20),
     transforms.ColorJitter(brightness=0.35, contrast=0.35),
     transforms.RandomResizedCrop(224, scale=(0.7, 1.2))
 ])

index = 1159
img, label = data[index]
plt.title(f"Label: {label}")
plt.imshow(img)

img_augmented = augment(img)
plt.figure()
plt.imshow(img_augmented)
# plt.imshow(img_augmented.permute(1,2,0)) //if in tensor form

# augmented data
X_train_aug = []
y_train_aug = []
for i in range(0,len(X_train)):
  img, label = X_train[i], y_train[i]
  for j in range(0,10):
    img_augmented = augment(img)
    X_train_aug.append(img_augmented)
    y_train_aug.append(label)

class CustomDataset(Dataset):

  def __init__(self, features, labels, transforms):

    self.features = features
    self.labels = labels
    self.transforms = transforms

  def __len__(self):

    return len(self.features)

  def __getitem__(self, index):

    image = self.features[index]
    image = self.transforms(image)
    return image, self.labels[index]

train_dataset = CustomDataset(X_train_aug, y_train_aug, custom_transform)
test_dataset = CustomDataset(X_test, y_test, custom_transform)
val_dataset = CustomDataset(X_val, y_val, custom_transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

model = resnet18(weights=ResNet18_Weights.DEFAULT)

model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)

model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 256),
    nn.ReLU(),
    nn.Dropout(0.3),

    nn.Linear(256, 128),
    nn.ReLU(),
    nn.Dropout(0.3),

    nn.Linear(128, 5)
)

# freezing resnet block and only training fc params
for param in model.parameters():
    param.requires_grad = False
for param in model.fc.parameters():
    param.requires_grad = True

from torchinfo import summary

summary(model, input_size=(1, 3, 224, 224))

model = model.to('cuda')
epochs = 75
lr = 0.001 # Reduced learning rate
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=lr, weight_decay=1e-4)

for epoch in range(epochs):

    model.train()
    train_correct = 0
    train_total = 0

    total_epoch_loss = 0

    for batch_features, batch_labels in train_loader:

        batch_features = batch_features.to('cuda')
        batch_labels = batch_labels.to('cuda')

        outputs = model(batch_features)

        loss = criteria(outputs, batch_labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_epoch_loss += loss.item()
        _, predicted = torch.max(outputs, 1)

        train_total += batch_labels.size(0)
        train_correct += (predicted == batch_labels).sum().item()

    train_loss = total_epoch_loss / len(train_loader)
    train_acc = 100 * train_correct / train_total

    model.eval()

    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for batch_features, batch_labels in val_loader:

            batch_features = batch_features.to('cuda')
            batch_labels = batch_labels.to('cuda')

            outputs = model(batch_features)

            loss = criteria(outputs, batch_labels)

            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)

            total += batch_labels.size(0)
            correct += (predicted == batch_labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc = 100 * correct / total

    print(
        f"Epoch {epoch+1}/{epochs} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Train Acc: {train_acc:.2f}% | "
        f"Val Acc: {val_acc:.2f}%"
    )

model.eval()

# Train accuracy
total = 0
correct = 0

with torch.no_grad():
   for batch_features,batch_labels in train_loader:

    # Moving to GPU
    batch_features, batch_labels = batch_features.to('cuda'), batch_labels.to('cuda')

    outputs = model(batch_features)

    predicted = torch.max(outputs,1) # 1 signifies dimension

    total += batch_labels.shape[0]

    correct += (predicted.indices == batch_labels).sum().item()

print(correct/total)

y_true = []
y_pred = []

with torch.no_grad():
   for batch_features,batch_labels in test_loader:

    # Moving to GPU
    batch_features, batch_labels = batch_features.to('cuda'), batch_labels.to('cuda')

    outputs = model(batch_features)

    _,predicted = torch.max(outputs,1) # 1 signifies dimension

    y_true.extend(batch_labels.cpu().numpy())
    y_pred.extend(predicted.cpu().numpy())

# Model Verification metrics

acc = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(y_true,y_pred,average='macro')

print(f"Test Accuracy: {acc*100:.2f}%")
print(f"Macro F1 Score: {macro_f1:.4f}")
print(classification_report(y_true,y_pred))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(cm,annot=True,fmt='d',cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

